Add probes for memfd_create and friends
elastic/ebpf pull request #185
Opened 2024-03-19 01:30 UTC by stanek-michal

New events added:

EBPF_EVENT_FILE_MEMFD_OPEN
EBPF_EVENT_FILE_SHMEM_OPEN
EBPF_EVENT_PROCESS_MEMFD_CREATE
EBPF_EVENT_PROCESS_SHMGET
EBPF_EVENT_PROCESS_PTRACE
EBPF_EVENT_PROCESS_LOAD_MODULE

Also added new fields to process exec event

2024-03-19 16:54 UTC, nicholasberlin reviewed
Nice work. A few questions.

2024-03-19 16:54 UTC, nicholasberlin commented on GPL/Events/File/Probe.bpf.c
> +        if ((path_prefix_len > 0) && (size >= path_prefix_len)) {
Why check `size >= path_prefix_len`? I think the current value in `size` is the cgroup path length.

2024-03-19 16:54 UTC, nicholasberlin commented on GPL/Events/File/Probe.bpf.c
> +            if (is_equal_prefix(field->data, path_prefix, path_prefix_len))
Not sure about `field->data` here.

2024-03-19 16:54 UTC, nicholasberlin commented on GPL/Events/Process/Probe.bpf.c
> +    if (!binprm)
-- bikeshedding --
This if block coud be moved to the beginning of the function to avoid filling pid, cred, and ctty info.
Also, other guard logic uses `goto out`, which in this case is equivalent to `return 0`, but I think they should be consistent.

All that said, I'm guessing this will effectively always be false so there will never be any efficiency gains from moving it.
-- /bikeshedding --

2024-03-19 16:54 UTC, nicholasberlin commented on GPL/Events/Process/Probe.bpf.c
> +        return 1;
What does returning 1 do?

2024-03-20 01:44 UTC, stanek-michal commented on GPL/Events/File/Probe.bpf.c
> +        if ((path_prefix_len > 0) && (size >= path_prefix_len)) {
thanks for spotting this, it's a rebase artifact, 'path' was supposed to be right above the path_prefix check

2024-03-20 01:59 UTC, stanek-michal commented on GPL/Events/Helpers.h
> +static int is_equal_prefix(const char *str1, const char *str2, int len)
I'm not 100% sure, but even if it didn't reject a case without fixed size arrays, it would probably just return 0 on a dereference if it was a bad page.

2024-03-20 02:08 UTC, stanek-michal commented on GPL/Events/Process/Probe.bpf.c
> +        return 1;
might have been a typo, but either way as far as I know the return value is not considered

2024-03-20 02:08 UTC, stanek-michal commented on GPL/Events/Process/Probe.bpf.c
> +    if (size < 0)
better change to <= 0

2024-03-20 13:19 UTC, nicholasberlin approved these changes
LGTM if it works

2024-05-02 17:45 UTC, mjwolf approved these changes
The multi-kernel tester has a failing test with this, I didn't look into the exact cause, but this LGTM, once the tests are fixed

2024-05-22 16:30 UTC, stanek-michal commented
> The multi-kernel tester has a failing test with this, I didn't look into the exact cause, but this LGTM, once the tests are fixed

turned out it was a missing `break` in a switch block in EventsTrace that sometimes would trigger memory corruption and fail the multi-kernel tests. Fixed now and rebased, rerunning CI

2024-05-22 21:30 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +    bool is_setgid;
Can we not use bool on things that show up on the wire, if you look at the rest of the file it uses properly sized types: uint32_t, int32_t and family, it even avoids using a single int.

2024-05-22 21:44 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +    event->is_setgid      = (BPF_CORE_READ(f_inode, i_mode) & S_ISGID) ? true : false;
nitpick, `&` has precedence, I'd zap the parenthesis

2024-05-22 21:47 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +    event->is_setgid      = (BPF_CORE_READ(f_inode, i_mode) & S_ISGID) ? true : false;
you can also do:
`event->is_setuid = !!(BPF_CORE_READ(f_inode, i_mode) & S_ISUID)`

2024-05-22 21:51 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +    if ((1 == curr_tgid) || (2 == curr_tgid) || (1 == ppid) || (2 == ppid))
can we avoid the 1 == curr_tgid, the rest of the repository uses curr_tgid == 1, I know this is endpoint leakage :D

2024-05-22 21:52 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +    if ((1 == curr_tgid) || (2 == curr_tgid) || (1 == ppid) || (2 == ppid))
can also zap the parenthesis, as == has precedence.

2024-05-22 21:53 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +
blank line

2024-05-22 21:54 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +    event->flag_cloexec     = (event->flags & MFD_CLOEXEC) ? true : false;
why do we have to express every flag isolated again in a member, can't the user just or the original flags?

2024-05-22 22:07 UTC, haesbaert commented on GPL/Events/Helpers.h
> +static int is_equal_prefix(const char *str1, const char *str2, int len)
I feel uneasy with this, and relying on the verifier solely seems not awesome, here is a valid alternative:
```
static int
strncmp(const char *s1, const char *s2, size_t n)
{

	if (n == 0)
		return (0);
	do {
		if (*s1 != *s2++)
			return (*(unsigned char *)s1 - *(unsigned char *)--s2);
		if (*s1++ == 0)
			break;
	} while (--n != 0);
	return (0);
}

// compares first 'len' characters of str1 and str2, returns 1 if equal
// NOTE: no bounds check, assumes use under eBPF verifier
static int is_equal_prefix(const char *str1, const char *str2, int len)
{
	return strncmp(str1, str2, len);
}

```

Compiles and runs with `EventsTrace --file-memfd-open --file-shmem-open --file-modify`

2024-05-22 22:11 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +    bool is_setgid;
Can we condense the 3 members into a uin32_t and use a flag for each bit?

2024-05-22 22:13 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +
As noted somewhere else, why do we express flags again? Those 5 bits are in flags already, so why do we need to place them alone again?
I'm just eyeballing, so apologies if I missed something.

2024-05-22 22:35 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +    bool is_setgid;
I've made this change that I think you can merge into this PR, my github-fu is severely limited, and as I said earlier, I ran out of goats:
https://github.com/elastic/ebpf/pull/194

2024-05-22 22:55 UTC, haesbaert requested changes
.

2024-05-23 12:20 UTC, stanek-michal commented on GPL/Events/Helpers.h
> +static int is_equal_prefix(const char *str1, const char *str2, int len)
lgtm, I'll replace it

2024-05-23 12:31 UTC, stanek-michal commented on GPL/Events/EbpfEventProto.h
> +    bool is_setgid;
agreed overall, there is an enum somewhere technically so it's not 100% portable but considering we want to be able to interface this from different languages, it's worth paying attention to

2024-05-23 12:32 UTC, stanek-michal commented on GPL/Events/Process/Probe.bpf.c
> +    event->is_setgid      = (BPF_CORE_READ(f_inode, i_mode) & S_ISGID) ? true : false;
that's one thing I do not agree with BSD folks, I like my parentheses and hate requiring everyone to know all precedence rules

2024-05-23 13:01 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +    bool is_setgid;
Agreed, it's more for harmony with the rest than being portable, but it does help with stuff like someone using 
Go and having to figure out what is the size of bool.

2024-05-23 13:03 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +    event->is_setgid      = (BPF_CORE_READ(f_inode, i_mode) & S_ISGID) ? true : false;
Fine by me, please disregard the other comments regarding precedence.
Now I'm in an existential crisis, am I still BSD folk, not even god knows :rofl: .

2024-05-28 07:10 UTC, haesbaert requested changes
Nice work, some very minor thingies

2024-05-28 07:10 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +        goto out;
```suggestion
    struct task_struct *task = (struct task_struct *)bpf_get_current_task();

    if (is_kernel_thread(task))
        goto out;

    struct ebpf_process_load_module_event *event = get_event_buffer();
    if (!event)
        goto out;

    event->hdr.type = EBPF_EVENT_PROCESS_LOAD_MODULE;
    event->hdr.ts   = bpf_ktime_get_ns();

```

Rest of the source checks task before getting event, I think we should keep the same pattern, pattern are goods and make for a healthy breakfast.

2024-05-28 07:10 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
> +
```suggestion
    struct task_struct *task = (struct task_struct *)bpf_get_current_task();
    if (is_kernel_thread(task))
        goto out;

    pid_t curr_tgid          = BPF_CORE_READ(task, tgid);
    pid_t child_ppid         = BPF_CORE_READ(child, group_leader, real_parent, tgid);
    pid_t child_tgid         = BPF_CORE_READ(child, tgid);
```
Don't bother reading things if we're about to bail

2024-05-28 07:10 UTC, haesbaert commented on cmake/modules/setup.cmake
> +    target_compile_options(${target} PUBLIC -g -Wall -Wextra)
does this apply to the whole repository?
I'm not very familiar with cmake, but I've added a bunch of flags in `non-GPL/CMakeLists.txt`, do they get merged?

2024-05-28 23:29 UTC, stanek-michal commented on GPL/Events/Helpers.h
> +static int is_equal_prefix(const char *str1, const char *str2, int len)
added at the top

2024-05-28 23:30 UTC, stanek-michal commented on GPL/Events/EbpfEventProto.h
> +    int32_t child_pid;
done

2024-05-28 23:30 UTC, stanek-michal commented on GPL/Events/EbpfEventProto.h
> +    int32_t key;
done

2024-05-28 23:30 UTC, stanek-michal commented on GPL/Events/Process/Probe.bpf.c
> +    char buf_filename[8]       = {0};
done

2024-05-28 23:30 UTC, stanek-michal commented on GPL/Events/Process/Probe.bpf.c
> +        goto out;
done

2024-05-28 23:30 UTC, stanek-michal commented on GPL/Events/Process/Probe.bpf.c
> +
done

2024-05-28 23:33 UTC, stanek-michal commented on cmake/modules/setup.cmake
> +    target_compile_options(${target} PUBLIC -g -Wall -Wextra)
I think this only applies to calls to ebpf_static_binary, like this one:
`ebpf_static_binary(EventsTrace`
so EventsTrace will have debug symbols.

As for your change, not sure but best way is to look at the compilation output and find the flags

2024-05-29 06:06 UTC, haesbaert approved these changes

2024-05-29 06:06 UTC, haesbaert commented
Looking swell!

2024-05-29 15:14 UTC, merged