Add UDP probes in anticipation of DNS monitoring
elastic/ebpf pull request #206
Opened 2024-08-30 18:56 UTC by fearful-symmetry

So, right now this PR is pretty functional and basic. It adds probes for `udp_sendmsg`/`udp_recvmsg` along with the needed tooling, and allows for monitoring of DNS and udp traffic, similar to the existing TCP probes:
```
sudo ./EventsTrace -i --net-conn-udp-recvmsg --net-conn-udp-sendmsg                                                                                          
{"probes_initialized": true, "features": {"bpf_tramp": true}}
{"event_type":"NETWORK_UDP_SENDMSG","pids":{"tid":111308,"tgid":111306,"ppid":101362,"pgid":111306,"sid":101362,"start_time_ns":167137253242835},"net":{"transport":"UDP","family":"AF_INET","source_address":"192.168.1.37","source_port":38277,"destination_address":"1.1.1.1","destination_port":53,"network_namespace":4026531840},"comm":"isc-net-0000"}
{"event_type":"NETWORK_UDP_RECVMSG","pids":{"tid":111308,"tgid":111306,"ppid":101362,"pgid":111306,"sid":101362,"start_time_ns":167137253242835},"net":{"transport":"UDP","family":"AF_INET","source_address":"192.168.1.37","source_port":38277,"destination_address":"1.1.1.1","destination_port":53,"network_namespace":4026531840},"comm":"isc-net-0000"}
```

Right now this is in draft because I'm unsure if this is the approach we want to take for DNS monitoring. The one remaining piece of this is actually reading DNS packets; using fentry/fexit this is (in theory) possible by reading the `iov_iter` struct. Where this gets complicated is pre-trampoline kernels---`kretprobe` doesn't have access to the function args, meaning we can't get the iovec data after it's been populated. 

There's some alternatives here, most notably using TC probes: https://ebpf-docs.dylanreimerink.nl/linux/program-type/BPF_PROG_TYPE_SCHED_CLS/ , which I haven't experimented with yet. 

How do we feel about this implementation? Should we use TC or PF_PACKET or something else if we actually want to fetch the packet data?

2024-09-02 14:39 UTC, stanek-michal commented
> using fentry/fexit this is (in theory) possible by reading the `iov_iter` struct. Where this gets complicated is pre-trampoline kernels---`kretprobe` doesn't have access to the function args, meaning we can't get the iovec data after it's been populated.

We could probably do the set_state/get_state trick that we have in Helpers.h which maintains state between entry and ret so that we get access to the input argument pointers in the handler for ret.

> There's some alternatives here, most notably using TC probes: https://ebpf-docs.dylanreimerink.nl/linux/program-type/BPF_PROG_TYPE_SCHED_CLS/ , which I haven't experimented with yet.

I believe this is where TC runs on the RX path:
https://elixir.bootlin.com/linux/v6.10.7/source/net/core/dev.c#L4049
so this is early, at L2, before `deliver_skb()` and before it reaches the IP layer. We probably cannot easily map it to the receiving process without having to maintain our own bookkeeping. We could experiment with [bpf_sk_lookup_tcp](https://patchwork.ozlabs.org/project/netdev/patch/20180921171043.20823-8-joe@wand.net.nz/) helper and see if its reliable - if it works as advertised it can get the listening socket just from the 5tuple so that could allow us to extract the PID easier probably. There's also `bpf_sk_fullsock()` which does...something.

Another thing is at this early L2 stage we don't even know if the packet will actually reach the application, there is quite a lot of filtering and drop scenarios in between.

So I think I'm leaning towards the hooks as they are done in this PR if we can easily get packet data there and parse it. I assume we want to filter for port 53 in the kernel and avoid creating events for other UDP packets otherwise there could be a lot.

2024-09-03 13:38 UTC, fearful-symmetry commented
@stanek-michal so, I did some tinkering over the three-day weekend and came to a lot of the conclusions you did, namely that we could use a state getter/setter for kretprobes, and also the problem with finding the userspace pid with a TC/classifier probe.


I'm leaning towards the getter/setter with kretprobe idea for this, since it's a little simpler (we don't need some other mechanism for tracking what userland process owns the pid).

2024-09-03 15:43 UTC, fearful-symmetry commented
Taking this out of draft since I think this is a fairly decent framework going forward if/when we want to parse DNS packets.

2024-09-06 14:29 UTC, haesbaert commented
This won't work for unconnected sockets, as the socket doesn't have an address, if you run the following program you will see the packets don't show up. Worth noting that unconnected udp sockets are likely more common than unconnected.

You can use the following program to verify:
```
./udpsend -c 8.8.8.8 # connected
./udpsend 8.8.8.8 # unconnected
```

```
#define _GNU_SOURCE 		/* program_invocation_name */
#include <sys/types.h>
#include <sys/socket.h>

#include <netinet/in.h>

#include <arpa/inet.h>

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <err.h>

static void
usage(void)
{
	fprintf(stderr, "usage: %s [-c] addr4",
	    program_invocation_short_name);

	exit(1);
}

int
main(int argc, char *argv[])
{
	struct sockaddr_in	sin;
	int			sock, ch, do_connect;
	ssize_t			n;
	uint64_t		buf[] = {
		0xdeadbeef, 0xdeadbeef, 0xdeadbeef, 0xdeadbeef,
		0xdeadbeef, 0xdeadbeef, 0xdeadbeef, 0xdeadbeef
	};

	do_connect = 0;
	while ((ch = getopt(argc, argv, "ch")) != -1) {
		switch (ch) {
		case 'c':
			do_connect = 1;
			break;
		default:
			usage();
		}
	}
	argc -= optind;
	argv += optind;

	bzero(&sin, sizeof(sin));

	if (inet_aton(argv[0], &sin.sin_addr) == 0)
		errx(1, "inet_aton(%s)", argv[0]);
	sin.sin_port = htons(53);
	sin.sin_family = AF_INET;

	if ((sock = socket(AF_INET, SOCK_DGRAM, 0)) == -1)
		err(1, "socket");

	if (do_connect) {
		if (connect(sock, (struct sockaddr *)&sin, sizeof(sin)) == -1)
			err(1, "connect");
		n = write(sock, buf, sizeof(buf));
		if (n == -1)
			err(1, "sendto");
		else if (n != sizeof(buf))
			errx(1, "sendto: shortcount");

		return (0);
	}

	n = sendto(sock, buf, sizeof(buf), 0,
	    (struct sockaddr *)&sin, sizeof(sin));
	if (n == -1)
		err(1, "sendto");
	else if (n != sizeof(buf))
		errx(1, "sendto: shortcount");

	return (0);
}

```

As I mentioned to you yesterday, I think this is still not a good place to tap, I'll do a proper review later tonight and have more comments, but if you use the program above with events trace you can spot the issue.

2024-09-09 12:28 UTC, nicholasberlin reviewed
Looking good, just a bit of clean up left I think. Oh, and the tests are not passing.

2024-09-09 12:28 UTC, nicholasberlin commented on non-GPL/Events/EventsTrace/EventsTrace.c
> +static void out_network_udp_sendmsg(struct ebpf_net_event *evnt)
delete this function?

2024-09-09 12:28 UTC, nicholasberlin commented on non-GPL/Events/EventsTrace/EventsTrace.c
> +static void out_network_udp_recvmsg(struct ebpf_net_event *evnt)
delete this function?

2024-09-09 12:28 UTC, nicholasberlin commented on GPL/Events/Network/Network.h
> +#define MSG_PEEK 2
I don't think these defines are used anymore.

2024-09-09 12:28 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +    uint8_t pkt[MAX_DNS_PACKET];
Will userspace be able to figure out if the entire array is not used? Do we need a packet length field?

2024-09-09 12:28 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +// int BPF_PROG(fentry__udp_sendmsg, struct sock *sk, struct msghdr *msg, size_t size)
delete?

2024-09-09 12:28 UTC, nicholasberlin commented on non-GPL/Events/EventsTrace/EventsTrace.c
> +static void out_network_udp_sendmsg(struct ebpf_net_event *evnt)
oh, nevermind. looks like it should be renamed though.

2024-09-09 12:28 UTC, nicholasberlin commented on non-GPL/Events/EventsTrace/EventsTrace.c
> +static void out_network_udp_recvmsg(struct ebpf_net_event *evnt)
oh, nevermind. looks like it should be renamed though.

2024-09-09 17:03 UTC, fearful-symmetry commented
Alright, so, reverted the commit that swapped over to the `*skb*` methods. This is back to using `udp_sendmsg` and `udp_recvmsg`. Will continue to investigate alternatives.

2024-09-11 11:46 UTC, haesbaert requested changes
This needs some work, but it's a step in the right direction imho.
It would be better to clean up the unused bits before asking for a review.
As we discussed yesterday, it's likely you want to use the varlen thingy to express the packet instead of hard coding it.
Let me know if anything is not clear.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +        bpf_core_read(&ip_hdr, sizeof(struct iphdr), data + net_header_offset);
This breaks endianess, the information you want is in iphdr:
```
struct iphdr {
#if defined(__LITTLE_ENDIAN_BITFIELD)
    __u8 ihl : 4, version : 4;
#elif defined(__BIG_ENDIAN_BITFIELD)
    __u8 version : 4, ihl : 4;
#else
#error "Please fix <asm/byteorder.h>"
#endif
    __u8 tos;
    __be16 tot_len;
    __be16 id;
    __be16 frag_off;
    __u8 ttl;
    __u8 protocol;
    __sum16 check;
    __be32 saddr;
    __be32 daddr;
    /*The options start here. */
};
```

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
Don't need to cast to `void *`

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +        bpf_probe_read(event->net.daddr6, 16, ip6_hdr.daddr.in6_u.u6_addr8);
I'm ignoring ipv6 for now.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +        bpf_printk("not a dns packet...");
filter before doing the filling, this should be way up.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    long offset = transport_header_offset + sizeof(struct udphdr);
size_t would fit this better.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    // get lengths
this is a very confusing name, as the skb itself has a data member.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    if (readsize > MAX_DNS_PACKET) {
`len` is not what you want, as what you want is the amount of linear data in the skb, `len` is the total, you want the equivalent of `skb_headlen`, which should be something like:
```
static inline unsigned int skb_headlen(const struct sk_buff *skb)
{
	return skb->len - skb->data_len;
}
```

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    long ret = bpf_probe_read_kernel(event->pkts[0].pkt, readsize, data + offset);
small nit, I'd prefer `data + transport_header_offset + sizeof(udphdr)`, less mental strain remembering what offset is, feel free to ignore.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
as mentioned before, you're writing a fixed size amount of data, instead of taking the size of the packet into account.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Process/Probe.bpf.c
should be in a different PR.

2024-09-11 11:46 UTC, haesbaert commented on non-GPL/Events/Lib/EbpfEvents.c
> +        err = err ?: bpf_program__set_autoload(obj->progs.kretprobe__skb_consume_udp, false);
kret isn't needed.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +    EBPF_EVENT_NETWORK_DNS_PKT              = (1 << 22),
only DNS_PKT is a header type, the other is metadata from DNS_PKT, it shouldn't be on the same space.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
as I mentioned before, I'd prefer if we send the whole packet to userland, including ip and udp headers.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Network.h
> +        net->transport = EBPF_NETWORK_EVENT_TRANSPORT_UDP;
This function is also never called for a udp socket, and you fill `ebpf_net_info` incompletely in `handle_consume`

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
`event->net` is incomplete, missing family and transport.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +        bpf_printk("not a dns packet...");
can't print things on a per-packet basis.

2024-09-11 11:46 UTC, haesbaert commented on non-GPL/Events/EventsTrace/EventsTrace.c
> +        break;
I don't think you ever hit this since net->transport is never filled.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    u64 pid_tid = bpf_get_current_pid_tgid();
don't need kretprobe as mentioned above.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    return 0;
all of this can go away, don't need the context.

2024-09-11 11:46 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    return handle_consume(skb, len, EBPF_EVENT_NETWORK_UDP_SEND);
everything should be derivable from skb, no need for socket or an additional len.

2024-09-11 17:56 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +
You mean as opposed to parsing it in ebpf, or in addition to parsing it in ebpf?

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +    EBPF_EVENT_NETWORK_DNS_PKT              = (1 << 22),
```suggestion
    EBPF_EVENT_NETWORK_DNS_PKT              = (1 << 20),
```

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/Network/Network.h
> +#define MSG_PEEK 2
I don't see this being used. Delete?

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +struct dns_body {
I think this struct can be deleted.

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +    // uint8_t pkt[MAX_DNS_PACKET];
```suggestion
```

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +int BPF_PROG(fexit__skb_consume_udp, struct sock *sk, struct sk_buff *skb, int len)
```suggestion
int BPF_PROG(fentry__skb_consume_udp, struct sock *sk, struct sk_buff *skb, int len)
```

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +int BPF_KPROBE(kprobe__skb_consume_udp, struct net *net, struct sk_buff *skb)
Why isn't `len` a parameter here, like the fentry version?

2024-09-11 19:53 UTC, nicholasberlin commented on non-GPL/Events/Lib/EbpfEvents.c
> +        err = err ?: bpf_program__set_autoload(obj->progs.fexit__skb_consume_udp, false);
```suggestion
        err = err ?: bpf_program__set_autoload(obj->progs.fentry__skb_consume_udp, false);
```

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +
```suggestion
```
don't need these lines, since we aren't doing anything in the `out` label.

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +        return 0;
Returning zero here implies to me that we want to avoid the handling in `out`, but `out` isn't doing anything. Should `goto out` for consistency.

2024-09-11 19:53 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +        return 0;
Should `goto out` for consistency.

2024-09-11 20:52 UTC, fearful-symmetry commented
Alright, tested on 6.10 and 5.15...

2024-09-12 11:16 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +    EBPF_EVENT_NETWORK_DNS_PKT              = (1 << 22),
This was resolved but I don't see the change. Forgot to commit/push?

2024-09-12 11:17 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +struct dns_body {
I don't see this change. Was I wrong? Is it needed?

2024-09-12 11:17 UTC, nicholasberlin commented on GPL/Events/EbpfEventProto.h
> +    // uint8_t pkt[MAX_DNS_PACKET];
I don't see this change. Why preserve it?

2024-09-12 11:18 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +int BPF_KPROBE(kprobe__skb_consume_udp, struct net *net, struct sk_buff *skb)
Should use also use the `len` parameter like the `fentry` version, right?

2024-09-12 11:20 UTC, nicholasberlin commented
I think we have settled on the skb functions, which means the previously excellent description needs some love.

2024-09-12 16:01 UTC, fearful-symmetry commented on GPL/Events/EbpfEventProto.h
> +    EBPF_EVENT_NETWORK_DNS_PKT              = (1 << 22),
Yup, accidentally editing the files in `artifacts/`

2024-09-12 16:12 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +int BPF_KPROBE(kprobe__skb_consume_udp, struct net *net, struct sk_buff *skb)
Ah, you mean check the `len`, thought you meant the parameter was missing from the probe.

2024-09-12 16:22 UTC, nicholasberlin commented on GPL/Events/Network/Probe.bpf.c
> +int BPF_KPROBE(kprobe__skb_consume_udp, struct net *net, struct sk_buff *skb)
Oops, should've been more clear. Change LGTM.

2024-09-12 16:26 UTC, haesbaert commented
I'll have a look on this tonight

2024-09-12 17:47 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
1500 is a better value, in essence a real valyue would be 1500 - sizeof(iphdr) - sizeof(udphdr), but 1500 is round.

2024-09-13 17:30 UTC, fearful-symmetry commented
So, did a bit more testing with large DNS queries using this: 
```
dig +noall +answer +comments @166.84.7.99 512.size.dns.netmeister.org a
```

Haven't noticed any weird paging behavior.

2024-09-17 08:53 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +        }
`lost` expresses lost events from kernel -> ringbuffer, feel free to add another member in `ebpf_event_stats`, like `zero_dns` or something.

2024-09-17 09:25 UTC, haesbaert requested changes
I didn't look much on the ipv6.
Summary is, the counter should be a new member, as `lost` is used basically to detect when we're too slow to read the ringbuffer.
Consistently check the errors of `bpf_*`, and validate data before mutating state (checking port/src before writign to event)

Maybe @nicholasberlin has more input

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
not to bikeshed, but didn't we figure this is the same as skb->data?

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    if (headlen > MAX_DNS_PACKET) {
```suggestion
    event->orig_len = headlen;
    if (headlen > MAX_DNS_PACKET) {
```

Just so that userland can detect truncation.

2024-09-17 09:25 UTC, haesbaert commented on non-GPL/Events/EventsTrace/EventsTrace.c
> +            printf("%02X ", part);
```suggestion
            printf("%02X", part);
```

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/EbpfEventProto.h
> +    EBPF_NETWORK_EVENT_IP_SEND_UDP     = 2,
you sure you don't want to rename these to something more generic? like send/recv?

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
```suggestion

        if (bpf_probe_read(event->net.saddr, 4, &ip_hdr.saddr) != 0) {
            goto out;
        }
        if (bpf_probe_read(event->net.daddr, 4, &ip_hdr.daddr) != 0) {
            goto out;
        }

        event->net.family = EBPF_NETWORK_EVENT_AF_INET;
    } else if (ip_hdr.version == 6) {
        struct ipv6hdr ip6_hdr;
        if (bpf_core_read(&ip6_hdr, sizeof(struct ipv6hdr), skb_head + net_header_offset) != 0) {
            goto out;
        }
        proto = ip6_hdr.nexthdr;

        if (bpf_probe_read(event->net.saddr6, 16, ip6_hdr.saddr.in6_u.u6_addr8) != 0) {
            goto out;
        }
        if (bpf_probe_read(event->net.daddr6, 16, ip6_hdr.daddr.in6_u.u6_addr8) != 0) {
            goto out;
        }

```

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +    bpf_core_read(&udp_hdr, sizeof(struct udphdr), skb_head + transport_header_offset);
```suggestion
    if (bpf_core_read(&udp_hdr, sizeof(struct udphdr), skb_head + transport_header_offset) != 0)
        goto out;
```

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
```suggestion

```

Moved the comparison before, this way all the `out` clauses are before we start writing to the ringbuffer.

2024-09-17 09:25 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +
just checking for the return value, rest of the code seems to be consistent.

2024-09-17 14:35 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
On some of the methods, no, `head` will start at the IP header, not the application layer body.

2024-09-17 14:40 UTC, fearful-symmetry commented on GPL/Events/EbpfEventProto.h
> +    EBPF_NETWORK_EVENT_IP_SEND_UDP     = 2,
Feels a little more descriptive this way, so userland has some data on what we're probing.

2024-09-17 14:53 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +
The github UI doesn't make it too clear where you moved it to, but I took a guess...

2024-09-17 16:51 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
If it starts at the IP header, how will userland know what to parse?

2024-09-17 16:56 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
Wait, maybe I missed something, shouldn't skb->data always be the payload of udp (the dns body)?

2024-09-18 17:05 UTC, nicholasberlin commented on testing/test_bins/udp_send.c
> +    create_buffer(buffer, sizeof(buffer));
this function could be replaced with:
```
memset(buffer, 0xff, sizeof(buffer));
```

but whatever.

2024-09-18 17:15 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
Sorry, should have been more clear. So, for `ip_send_skb`, `body` seems to start at the IP header, not the application body. However, the offsets at `skb->network_header` and `skb->transport_header` are still correct, so as long as we read from `skb->head + offsets`, we'll start reading from the beginning of the application body, so it won't start at the IP header.

However, as I type this, I realize it should be possible to just read from `skb->head + skb->transport_header`, which is as bit simpler. Let me try that...

2024-09-18 17:21 UTC, nicholasberlin commented on testing/test_bins/udp_send.c
> +}
```suggestion
```
Since you are using `memset`, can delete this.

2024-09-18 17:26 UTC, haesbaert commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
What is body?
Do you mean that skb->data is the start of ip?
Can you just show print skb->data on receive and incoming so we can see?

2024-09-18 17:28 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
Nevermind, I confused myself, `skb->head + skb->transport_header` is the _beginning_ of the UDP header, hence `+ sizeof(struct udphdr)`

2024-09-18 18:37 UTC, fearful-symmetry commented on GPL/Events/Network/Probe.bpf.c
> +                                     skb_head + transport_header_offset + sizeof(struct udphdr));
So, this is the first couple bytes of `data` from `ip_send_skb`:
```
[69, 0, 0, 0, 25, 238, 0, 0, 64, 17, 0, 0, 127, 0, 0, 1, 127, 0, 0, 53, 202, 196, 0, 53, 0, 59, 254, 130, 236, 132, 1, 32, 0, 1, 0, 0, 0, 0, 0, 1, 6, 103, 105, 116, 104, 117, 98, 3, 99, 111, 109]}
```

That looks like the IP header, you can even see the addresses ( `127, 0, 0, 1, 127, 0, 0, 53,`).

This is `data` in `skb_consume_udp`:

```
[236, 132, 1, 32, 0, 1, 0, 0, 0, 0, 0, 1, 6, 103, 105, 116, 104, 117, 98, 3, 99, 111, 109, 0, 0, 1, 0, 1, 0, 0, 41, 4, 208, 0, 0, 0, 0, 0, 12, 0, 10, 0, 8, 82, 206, 183, 136, 107, 47, 147, 50]
```

That starts at the DNS packet; the first two bytes are the query id (236, 132), which you can _also_ see in the first packet, after the headers.

2024-09-19 06:01 UTC, haesbaert requested changes
Missing an error case in sendto, and just make the test more idiomatic.
I wonder, why not use the udpsend I wrote in the PR? that way you can test both connected and unconnected, not that it makes a difference now.
At any rate I'm fine with this given this changes.

2024-09-19 18:25 UTC, haesbaert commented
I haven't tested the last iteration but looks good to me, good work!

2024-09-19 18:26 UTC, haesbaert approved these changes

2024-09-23 12:19 UTC, nicholasberlin approved these changes

2024-09-23 15:36 UTC, merged