docs(proposals): brain dump on feature detection for eBPF
elastic/ebpf pull request #39
Opened 2021-11-15 19:15 UTC by leodido

Hello all! 👋 

Opening this proposal about feature detection.

It is a first, initial draft that dumps everything I have on my brain about feature detection for eBPF.

I'd like to get to know your feedback.

Think of this as a discussion starter.

2021-11-15 20:59 UTC, nicholasberlin commented
I like the idea of having separate eBPF programs using different features. When there are a lot of `#ifdef`s in a single code base, the code reuse benefit starts to be overcome by the confusion added by mentally parsing `#ifdef`s.

If we decide on the runtime route, the code utilizing bpfhaz lib would have to know the requirements of what it's loading. The loading code, `bpfhaz` lib, and the eBPF programs would all need to be kept in sync. Is it possible to examine the eBPF .o's to know what is required?

Is there any harm in attempting to load the latest and greatest program set, and backing off to less feature rich sets until something successfully loads?

Is it possible to successfully load a program that won't work because a feature is missing?

2021-11-16 08:52 UTC, fntlnz commented
Thanks @leodido ! I like this proposal and I'd love to see it implemented.

I particularly like the fact that this is very flexible and that the API can be used to build other checks on top of it.

cc/ @ferullo @stanek-michal @tabell

2021-11-16 09:53 UTC, leodido reviewed
Fix some typos

2021-11-16 09:53 UTC, leodido commented on docs/proposals/feature-detection.md
> +has_helper_for_prog("bpf_get_stackid", BPF_PROG_TYPE_TRACING, false);
```suggestion
has_map(BPF_MAP_TYPE_LPM_TRIE, false, 0);
has_prog(BPF_PROG_TYPE_LSM, false, 0);
has_prog(BPF_PROG_TYPE_SCHED_CLS, false, 2/*eth0*/);
has_prog(BPF_PROG_SOCKET_FILTER, true, 0);
has_helper_for_prog("bpf_get_stackid", BPF_PROG_TYPE_TRACING, false, 0);
```

2021-11-16 09:53 UTC, leodido commented on docs/proposals/feature-detection.md
> +- It is a the approach more common used in eBPF land (as of today at least)
```suggestion
- It is the approach more commonly used in eBPF land (as of today at least)
```

2021-11-16 09:53 UTC, leodido commented on docs/proposals/feature-detection.md
> +The `if_idx` argument is only relevant when greather than 0, pointing to a device interface (device target).
```suggestion
The `if_idx` argument is only relevant when greater than 0, pointing to a device interface (device target, eg. 1 being `lo` iface, 2, etc.).
```

2021-11-16 10:07 UTC, leodido commented
> I like the idea of having separate eBPF programs using different features. When there are a lot of `#ifdef`s in a single code base, the code reuse benefit starts to be overcome by the confusion added by mentally parsing `#ifdef`s.

Totally agree.

> If we decide on the runtime route, the code utilizing bpfhaz lib would have to know the requirements of what it's loading. The loading code, `bpfhaz` lib, and the eBPF programs would all need to be kept in sync. Is it possible to examine the eBPF .o's to know what is required?

It is very possible to understand what we need by parsing the ELF. It's what `libbpf` already does.
Furthermore, if we end up generating skeletons and loading them we could simply read such objects (so no parsing, just navigating objects) and understand the map types and program types.
Detecting the helpers can be done by iterating over the instructions and looking up for `call ID` instructions, from the ID you obtain the helper name looking it up in BTF info.

So it's doable and also ~ already done depending on the approach we end up using for loading the programs. :)

> Is there any harm in attempting to load the latest and greatest program set, and backing off to less feature rich sets until something successfully loads?

Hmmm, the only type of harm (that I can think of rn) this could cause is described by the example below.
 
> Is it possible to successfully load a program that won't work because a feature is missing?

Yes.

The first example that comes to my mind is `bpf_printk`.

Newer versions (on newer kernels) of this helper accept more than one "%s" qualifier in the format, it understands "%pI4" qualifier, etc.
If you use those new features on an older kernel, the eBPF verifier accepts them, and the program loads but does not work when reaching that instruction...

Notice, I omitted in the current proposal, how to detect "which version" of the helper we have. That's for a follow-up iteration (wanted to keep it simple) :)

My memory tells me that I met other similar cases but I can wrap my head to remember them at the moment.

2021-11-16 14:13 UTC, leodido commented on docs/proposals/feature-detection.md
> +      3. kallsysm (`/proc/sys/net/core/bpf_jit_kallsyms`)
Typo

2021-11-16 14:14 UTC, leodido commented on docs/proposals/feature-detection.md
> +#### Stateful higher-level API
Will expand further on this ASAP

2021-11-23 16:53 UTC, rockdaboot commented on docs/proposals/feature-detection.md
> +Finally, it is imporant noticing that the third and last aspect to consider is the **target** we are probing.
Typo: imporant -> important

2021-11-23 16:54 UTC, rockdaboot commented on docs/proposals/feature-detection.md
> +We may build a API like the following (in pseudo-code):
a -> an

2021-11-23 16:56 UTC, rockdaboot commented on docs/proposals/feature-detection.md
> +this means we may ending up writing different eBPF programs for the same feature with different implementation (eg., perf buffer vs ring buffer)
-> implementations

2021-11-23 16:56 UTC, rockdaboot commented on docs/proposals/feature-detection.md
> +and load one or the other depeding on the feature existence we detect before loading.
-> depending

2021-11-23 17:02 UTC, rockdaboot commented on docs/proposals/feature-detection.md
> +the API should in that case lower the privileges is using. Then, proceed as normal.
is -> it is  or just drop `is using`.

2021-11-23 17:03 UTC, rockdaboot commented on docs/proposals/feature-detection.md
> +In such case, I advice to just return `false` for the specific feature being probed even if we can't really know if it would be available with more privileges or not.
-> such a case

2021-11-23 17:09 UTC, syscll requested changes
Really great document! Sorry for the nits.

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +this means we may ending up writing different eBPF programs for the same feature with different implementation (eg., perf buffer vs ring buffer)
```suggestion
this means we may end up writing different eBPF programs for the same feature with different implementation (eg., perf buffer vs ring buffer)
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +Notice that global data sections for eBPF programs requires kernel 5.2. But the same overall behavior can be achieved with plain eBPF maps.
```suggestion
Notice that global data sections for eBPF programs require kernel 5.2. But the same overall behavior can be achieved with plain eBPF maps.
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +the API should in that case lower the privileges is using. Then, proceed as normal.
```suggestion
the API should in that case lower the privileges it's using. Then, proceed as normal.
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +If the API user wants to explicitly probe feature existence for unprivileged use case while it has the full privileges,
```suggestion
If the API user wants to explicitly probe feature existence for unprivileged use cases while it has the full privileges,
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +In such case, I advice to just return `false` for the specific feature being probed even if we can't really know if it would be available with more privileges or not.
```suggestion
In such cases, I advise to just return `false` for the specific feature being probed even if we can't really know if it would be available with more privileges or not.
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +To avoid writing a parser for the Kernel config, a easier/cleaner approach
```suggestion
To avoid writing a parser for the Kernel config, an easier/cleaner approach
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +But such approach requires anyways the Kernel config (eg., `/proc/config.gz`).
```suggestion
But such approaches require the Kernel config (eg., `/proc/config.gz`).
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +So, we can define DAGs (or FSMs) to declaratively express feature detection at **an higher granularity level**.
```suggestion
So, we can define DAGs (or FSMs) to declaratively express feature detection at **a higher granularity level**.
```

2021-11-23 17:09 UTC, syscll commented on docs/proposals/feature-detection.md
> +Ipothetically, a top layer API, rather than issuing a call instruction to test the availability of a given helper,
```suggestion
Hypothetically, a top layer API, rather than issuing a call instruction to test the availability of a given helper,
```

2021-11-24 00:11 UTC, rhysre commented
I'll echo @nicholasberlin 's comment about not going the macro-generation route to avoid lots and lots of preprocessor defines. That was the way we did things at Cmd and, although it works well enough for our current use cases, I can see it really starting to clutter things up in the future.

The only minor concern I would have if we went the other way (and this could very well be unfounded) would be about us having to maintain an unreasonable number of probe codebases. Consider, for instance, four BPF features, A, B, C and D, with kernels existing that have features A, AB, ABC and ABCD. If those features were all relevant to us, we might have to maintain four separate sets of slightly different probes, keeping them in sync when we make new changes and add new features. I'd wager it would be pretty easy to cut the number of probe codebases down (eg. maybe we just do two sets, A and ABCD if we figure the number of kernels with AB and ABC are rather low), but some food for though nonetheless.

Regardless, I like that approach over macro generation.

> Is there any harm in attempting to load the latest and greatest program set, and backing off to less feature rich sets until something successfully loads?
>
> Is it possible to successfully load a program that won't work because a feature is missing?

I think this is definitely worth exploring, but would be hesitant about it. While I can't think of any examples offhand (besides the `printk` issue Leo brought up) I don't think there's a formal guarantee that any program requiring feature X will fail to load because feature X is missing. Off the top of my head I'd prefer explicit checks for features in the endpoint codebase before we try to load something.

2021-11-25 11:12 UTC, leodido commented
> I'll echo @nicholasberlin 's comment about not going the macro-generation route to avoid lots and lots of preprocessor defines. That was the way we did things at Cmd and, although it works well enough for our current use cases, I can see it really starting to clutter things up in the future.

So, it seems we all agree on the fact that the macro-generation approach is a no-go for us! 
I listed it because I wanted to give a complete view of the possibilities so that we all could make an informed decision. :)

> The only minor concern I would have if we went the other way (and this could very well be unfounded) would be about us having to maintain an unreasonable number of probe codebases. Consider, for instance, four BPF features, A, B, C and D, with kernels existing that have features A, AB, ABC and ABCD. If those features were all relevant to us, we might have to maintain four separate sets of slightly different probes, keeping them in sync when we make new changes and add new features. I'd wager it would be pretty easy to cut the number of probe codebases down (eg. maybe we just do two sets, A and ABCD if we figure the number of kernels with AB and ABC are rather low), but some food for thought nonetheless.

Yes. Theoretically, we could tend towards an explosion of programs.
This is one of the reasons I envision two APIs (as written down in the document): one to check the existence of single features (eg., is `BPF_PROG_TYPE_LSM` available?), and another (built on top of the first) checking whether the whole feature is actually usable (see the FSM example for checking BPF LSM support).

In fact, having `BPF_PROG_TYPE_LSM` (the "single" feature) does not guarantee we can run BPF LSM programs.

So, I'm fairly confident we will end up checking for "whole" features and the number of resulting probes will depend on them, not on single features. This reduces a lot the number of different probes to write/support and to keep in sync.

Furthermore, it's worth mentioning that in some (edge) cases we could also adopt a mixed approach.
Ie., moving the feature detection from the loading phase to the eBPF ELF with macros for single features, so as to reduce again the number of possible resulting probes.

My only concern for this mixed approach is it can easily degenerate into a mess (like if we went for the macro approach, or worse) in case we do not set up a strict and clear set of rules for when to use it and when not.

Overall, I believe that the combinatorial explosion is unlikely because of the reasons stated above.

> Regardless, I like that approach over macro generation.

YaY!

2021-11-25 11:13 UTC, leodido commented on docs/proposals/feature-detection.md
> +Finally, it is imporant noticing that the third and last aspect to consider is the **target** we are probing.
```suggestion
Finally, it is important to notice that the third and last aspect to consider is the **target** we are probing.
```

2021-11-25 11:13 UTC, leodido commented on docs/proposals/feature-detection.md
> +We may build a API like the following (in pseudo-code):
```suggestion
We may build an API like the following (in pseudo-code):
```

2021-11-25 11:13 UTC, leodido commented on docs/proposals/feature-detection.md
> +this means we may ending up writing different eBPF programs for the same feature with different implementation (eg., perf buffer vs ring buffer)
```suggestion
this means we may ending up writing different eBPF programs for the same feature with different implementations (eg., perf buffer vs ring buffer)
```

2021-12-21 18:41 UTC, fntlnz approved these changes
I like this proposal, we can use this as a starting point for an implementation.

LGTM

2022-02-02 22:34 UTC, rhysre approved these changes

2022-02-15 15:20 UTC, merged